/*
 * This file is generated by jOOQ.
 */
package io.jking.untitled.jooq.tables.records;


import io.jking.untitled.jooq.tables.GuildTickets;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildTicketsRecord extends UpdatableRecordImpl<GuildTicketsRecord> implements Record6<Integer, Long, Long, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_tickets.id</code>.
     */
    public GuildTicketsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.guild_tickets.guild_id</code>.
     */
    public GuildTicketsRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_tickets.creator_id</code>.
     */
    public GuildTicketsRecord setCreatorId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.creator_id</code>.
     */
    public Long getCreatorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_tickets.ticket_text</code>.
     */
    public GuildTicketsRecord setTicketText(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.ticket_text</code>.
     */
    public String getTicketText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.guild_tickets.timestamp</code>.
     */
    public GuildTicketsRecord setTimestamp(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.timestamp</code>.
     */
    public String getTimestamp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.guild_tickets.ticket_number</code>.
     */
    public GuildTicketsRecord setTicketNumber(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.ticket_number</code>.
     */
    public Integer getTicketNumber() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Long, Long, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Long, Long, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GuildTickets.GUILD_TICKETS.ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildTickets.GUILD_TICKETS.GUILD_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildTickets.GUILD_TICKETS.CREATOR_ID;
    }

    @Override
    public Field<String> field4() {
        return GuildTickets.GUILD_TICKETS.TICKET_TEXT;
    }

    @Override
    public Field<String> field5() {
        return GuildTickets.GUILD_TICKETS.TIMESTAMP;
    }

    @Override
    public Field<Integer> field6() {
        return GuildTickets.GUILD_TICKETS.TICKET_NUMBER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public Long component3() {
        return getCreatorId();
    }

    @Override
    public String component4() {
        return getTicketText();
    }

    @Override
    public String component5() {
        return getTimestamp();
    }

    @Override
    public Integer component6() {
        return getTicketNumber();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public Long value3() {
        return getCreatorId();
    }

    @Override
    public String value4() {
        return getTicketText();
    }

    @Override
    public String value5() {
        return getTimestamp();
    }

    @Override
    public Integer value6() {
        return getTicketNumber();
    }

    @Override
    public GuildTicketsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value3(Long value) {
        setCreatorId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value4(String value) {
        setTicketText(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value5(String value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value6(Integer value) {
        setTicketNumber(value);
        return this;
    }

    @Override
    public GuildTicketsRecord values(Integer value1, Long value2, Long value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildTicketsRecord
     */
    public GuildTicketsRecord() {
        super(GuildTickets.GUILD_TICKETS);
    }

    /**
     * Create a detached, initialised GuildTicketsRecord
     */
    public GuildTicketsRecord(Integer id, Long guildId, Long creatorId, String ticketText, String timestamp, Integer ticketNumber) {
        super(GuildTickets.GUILD_TICKETS);

        setId(id);
        setGuildId(guildId);
        setCreatorId(creatorId);
        setTicketText(ticketText);
        setTimestamp(timestamp);
        setTicketNumber(ticketNumber);
    }
}
