/*
 * This file is generated by jOOQ.
 */
package io.jking.untitled.jooq.tables.records;


import io.jking.untitled.jooq.tables.GuildData;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildDataRecord extends UpdatableRecordImpl<GuildDataRecord> implements Record5<Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_data.guild_id</code>.
     */
    public GuildDataRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_data.owner_id</code>.
     */
    public GuildDataRecord setOwnerId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_data.ticket_manager</code>.
     */
    public GuildDataRecord setTicketManager(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_manager</code>.
     */
    public Long getTicketManager() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_data.ticket_channel</code>.
     */
    public GuildDataRecord setTicketChannel(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_channel</code>.
     */
    public Long getTicketChannel() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.guild_data.log_channel</code>.
     */
    public GuildDataRecord setLogChannel(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.log_channel</code>.
     */
    public Long getLogChannel() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildData.GUILD_DATA.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildData.GUILD_DATA.OWNER_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildData.GUILD_DATA.TICKET_MANAGER;
    }

    @Override
    public Field<Long> field4() {
        return GuildData.GUILD_DATA.TICKET_CHANNEL;
    }

    @Override
    public Field<Long> field5() {
        return GuildData.GUILD_DATA.LOG_CHANNEL;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getOwnerId();
    }

    @Override
    public Long component3() {
        return getTicketManager();
    }

    @Override
    public Long component4() {
        return getTicketChannel();
    }

    @Override
    public Long component5() {
        return getLogChannel();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getOwnerId();
    }

    @Override
    public Long value3() {
        return getTicketManager();
    }

    @Override
    public Long value4() {
        return getTicketChannel();
    }

    @Override
    public Long value5() {
        return getLogChannel();
    }

    @Override
    public GuildDataRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildDataRecord value2(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public GuildDataRecord value3(Long value) {
        setTicketManager(value);
        return this;
    }

    @Override
    public GuildDataRecord value4(Long value) {
        setTicketChannel(value);
        return this;
    }

    @Override
    public GuildDataRecord value5(Long value) {
        setLogChannel(value);
        return this;
    }

    @Override
    public GuildDataRecord values(Long value1, Long value2, Long value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildDataRecord
     */
    public GuildDataRecord() {
        super(GuildData.GUILD_DATA);
    }

    /**
     * Create a detached, initialised GuildDataRecord
     */
    public GuildDataRecord(Long guildId, Long ownerId, Long ticketManager, Long ticketChannel, Long logChannel) {
        super(GuildData.GUILD_DATA);

        setGuildId(guildId);
        setOwnerId(ownerId);
        setTicketManager(ticketManager);
        setTicketChannel(ticketChannel);
        setLogChannel(logChannel);
    }
}
