/*
 * This file is generated by jOOQ.
 */
package io.jking.untitled.jooq.tables.records;


import io.jking.untitled.jooq.tables.GuildSettings;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildSettingsRecord extends UpdatableRecordImpl<GuildSettingsRecord> implements Record8<Long, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_settings.guild_id</code>.
     */
    public GuildSettingsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_settings.message_logging</code>.
     */
    public GuildSettingsRecord setMessageLogging(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.message_logging</code>.
     */
    public Boolean getMessageLogging() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.guild_settings.alt_logging</code>.
     */
    public GuildSettingsRecord setAltLogging(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.alt_logging</code>.
     */
    public Boolean getAltLogging() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.guild_settings.pfp_logging</code>.
     */
    public GuildSettingsRecord setPfpLogging(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.pfp_logging</code>.
     */
    public Boolean getPfpLogging() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.guild_settings.auto_mod</code>.
     */
    public GuildSettingsRecord setAutoMod(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.auto_mod</code>.
     */
    public Boolean getAutoMod() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.guild_settings.auto_alt</code>.
     */
    public GuildSettingsRecord setAutoAlt(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.auto_alt</code>.
     */
    public Boolean getAutoAlt() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.guild_settings.auto_pfp</code>.
     */
    public GuildSettingsRecord setAutoPfp(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.auto_pfp</code>.
     */
    public Boolean getAutoPfp() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.guild_settings.auto_message</code>.
     */
    public GuildSettingsRecord setAutoMessage(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_settings.auto_message</code>.
     */
    public Boolean getAutoMessage() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildSettings.GUILD_SETTINGS.GUILD_ID;
    }

    @Override
    public Field<Boolean> field2() {
        return GuildSettings.GUILD_SETTINGS.MESSAGE_LOGGING;
    }

    @Override
    public Field<Boolean> field3() {
        return GuildSettings.GUILD_SETTINGS.ALT_LOGGING;
    }

    @Override
    public Field<Boolean> field4() {
        return GuildSettings.GUILD_SETTINGS.PFP_LOGGING;
    }

    @Override
    public Field<Boolean> field5() {
        return GuildSettings.GUILD_SETTINGS.AUTO_MOD;
    }

    @Override
    public Field<Boolean> field6() {
        return GuildSettings.GUILD_SETTINGS.AUTO_ALT;
    }

    @Override
    public Field<Boolean> field7() {
        return GuildSettings.GUILD_SETTINGS.AUTO_PFP;
    }

    @Override
    public Field<Boolean> field8() {
        return GuildSettings.GUILD_SETTINGS.AUTO_MESSAGE;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Boolean component2() {
        return getMessageLogging();
    }

    @Override
    public Boolean component3() {
        return getAltLogging();
    }

    @Override
    public Boolean component4() {
        return getPfpLogging();
    }

    @Override
    public Boolean component5() {
        return getAutoMod();
    }

    @Override
    public Boolean component6() {
        return getAutoAlt();
    }

    @Override
    public Boolean component7() {
        return getAutoPfp();
    }

    @Override
    public Boolean component8() {
        return getAutoMessage();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Boolean value2() {
        return getMessageLogging();
    }

    @Override
    public Boolean value3() {
        return getAltLogging();
    }

    @Override
    public Boolean value4() {
        return getPfpLogging();
    }

    @Override
    public Boolean value5() {
        return getAutoMod();
    }

    @Override
    public Boolean value6() {
        return getAutoAlt();
    }

    @Override
    public Boolean value7() {
        return getAutoPfp();
    }

    @Override
    public Boolean value8() {
        return getAutoMessage();
    }

    @Override
    public GuildSettingsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildSettingsRecord value2(Boolean value) {
        setMessageLogging(value);
        return this;
    }

    @Override
    public GuildSettingsRecord value3(Boolean value) {
        setAltLogging(value);
        return this;
    }

    @Override
    public GuildSettingsRecord value4(Boolean value) {
        setPfpLogging(value);
        return this;
    }

    @Override
    public GuildSettingsRecord value5(Boolean value) {
        setAutoMod(value);
        return this;
    }

    @Override
    public GuildSettingsRecord value6(Boolean value) {
        setAutoAlt(value);
        return this;
    }

    @Override
    public GuildSettingsRecord value7(Boolean value) {
        setAutoPfp(value);
        return this;
    }

    @Override
    public GuildSettingsRecord value8(Boolean value) {
        setAutoMessage(value);
        return this;
    }

    @Override
    public GuildSettingsRecord values(Long value1, Boolean value2, Boolean value3, Boolean value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildSettingsRecord
     */
    public GuildSettingsRecord() {
        super(GuildSettings.GUILD_SETTINGS);
    }

    /**
     * Create a detached, initialised GuildSettingsRecord
     */
    public GuildSettingsRecord(Long guildId, Boolean messageLogging, Boolean altLogging, Boolean pfpLogging, Boolean autoMod, Boolean autoAlt, Boolean autoPfp, Boolean autoMessage) {
        super(GuildSettings.GUILD_SETTINGS);

        setGuildId(guildId);
        setMessageLogging(messageLogging);
        setAltLogging(altLogging);
        setPfpLogging(pfpLogging);
        setAutoMod(autoMod);
        setAutoAlt(autoAlt);
        setAutoPfp(autoPfp);
        setAutoMessage(autoMessage);
    }
}
