/*
 * This file is generated by jOOQ.
 */
package io.jking.untitled.jooq.tables.records;


import io.jking.untitled.jooq.tables.GuildData;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildDataRecord extends UpdatableRecordImpl<GuildDataRecord> implements Record6<Long, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_data.guild_id</code>.
     */
    public GuildDataRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_data.owner_id</code>.
     */
    public GuildDataRecord setOwnerId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_data.logs_id</code>.
     */
    public GuildDataRecord setLogsId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.logs_id</code>.
     */
    public Long getLogsId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_data.moderator_id</code>.
     */
    public GuildDataRecord setModeratorId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.moderator_id</code>.
     */
    public Long getModeratorId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.guild_data.notifications_id</code>.
     */
    public GuildDataRecord setNotificationsId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.notifications_id</code>.
     */
    public Long getNotificationsId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.guild_data.ticket_id</code>.
     */
    public GuildDataRecord setTicketId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_id</code>.
     */
    public Long getTicketId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildData.GUILD_DATA.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildData.GUILD_DATA.OWNER_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildData.GUILD_DATA.LOGS_ID;
    }

    @Override
    public Field<Long> field4() {
        return GuildData.GUILD_DATA.MODERATOR_ID;
    }

    @Override
    public Field<Long> field5() {
        return GuildData.GUILD_DATA.NOTIFICATIONS_ID;
    }

    @Override
    public Field<Long> field6() {
        return GuildData.GUILD_DATA.TICKET_ID;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getOwnerId();
    }

    @Override
    public Long component3() {
        return getLogsId();
    }

    @Override
    public Long component4() {
        return getModeratorId();
    }

    @Override
    public Long component5() {
        return getNotificationsId();
    }

    @Override
    public Long component6() {
        return getTicketId();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getOwnerId();
    }

    @Override
    public Long value3() {
        return getLogsId();
    }

    @Override
    public Long value4() {
        return getModeratorId();
    }

    @Override
    public Long value5() {
        return getNotificationsId();
    }

    @Override
    public Long value6() {
        return getTicketId();
    }

    @Override
    public GuildDataRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildDataRecord value2(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public GuildDataRecord value3(Long value) {
        setLogsId(value);
        return this;
    }

    @Override
    public GuildDataRecord value4(Long value) {
        setModeratorId(value);
        return this;
    }

    @Override
    public GuildDataRecord value5(Long value) {
        setNotificationsId(value);
        return this;
    }

    @Override
    public GuildDataRecord value6(Long value) {
        setTicketId(value);
        return this;
    }

    @Override
    public GuildDataRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildDataRecord
     */
    public GuildDataRecord() {
        super(GuildData.GUILD_DATA);
    }

    /**
     * Create a detached, initialised GuildDataRecord
     */
    public GuildDataRecord(Long guildId, Long ownerId, Long logsId, Long moderatorId, Long notificationsId, Long ticketId) {
        super(GuildData.GUILD_DATA);

        setGuildId(guildId);
        setOwnerId(ownerId);
        setLogsId(logsId);
        setModeratorId(moderatorId);
        setNotificationsId(notificationsId);
        setTicketId(ticketId);
    }
}
