/*
 * This file is generated by jOOQ.
 */
package io.jking.untitled.jooq.tables.records;


import io.jking.untitled.jooq.tables.GuildInfractions;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildInfractionsRecord extends TableRecordImpl<GuildInfractionsRecord> implements Record6<Long, Long, Integer, String, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_infractions.guild_id</code>.
     */
    public GuildInfractionsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_infractions.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_infractions.target_id</code>.
     */
    public GuildInfractionsRecord setTargetId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_infractions.target_id</code>.
     */
    public Long getTargetId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_infractions.case_number</code>.
     */
    public GuildInfractionsRecord setCaseNumber(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_infractions.case_number</code>.
     */
    public Integer getCaseNumber() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.guild_infractions.reason</code>.
     */
    public GuildInfractionsRecord setReason(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_infractions.reason</code>.
     */
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.guild_infractions.issuer_id</code>.
     */
    public GuildInfractionsRecord setIssuerId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_infractions.issuer_id</code>.
     */
    public Long getIssuerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.guild_infractions.timestamp</code>.
     */
    public GuildInfractionsRecord setTimestamp(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_infractions.timestamp</code>.
     */
    public String getTimestamp() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Integer, String, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Integer, String, Long, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildInfractions.GUILD_INFRACTIONS.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildInfractions.GUILD_INFRACTIONS.TARGET_ID;
    }

    @Override
    public Field<Integer> field3() {
        return GuildInfractions.GUILD_INFRACTIONS.CASE_NUMBER;
    }

    @Override
    public Field<String> field4() {
        return GuildInfractions.GUILD_INFRACTIONS.REASON;
    }

    @Override
    public Field<Long> field5() {
        return GuildInfractions.GUILD_INFRACTIONS.ISSUER_ID;
    }

    @Override
    public Field<String> field6() {
        return GuildInfractions.GUILD_INFRACTIONS.TIMESTAMP;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getTargetId();
    }

    @Override
    public Integer component3() {
        return getCaseNumber();
    }

    @Override
    public String component4() {
        return getReason();
    }

    @Override
    public Long component5() {
        return getIssuerId();
    }

    @Override
    public String component6() {
        return getTimestamp();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getTargetId();
    }

    @Override
    public Integer value3() {
        return getCaseNumber();
    }

    @Override
    public String value4() {
        return getReason();
    }

    @Override
    public Long value5() {
        return getIssuerId();
    }

    @Override
    public String value6() {
        return getTimestamp();
    }

    @Override
    public GuildInfractionsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildInfractionsRecord value2(Long value) {
        setTargetId(value);
        return this;
    }

    @Override
    public GuildInfractionsRecord value3(Integer value) {
        setCaseNumber(value);
        return this;
    }

    @Override
    public GuildInfractionsRecord value4(String value) {
        setReason(value);
        return this;
    }

    @Override
    public GuildInfractionsRecord value5(Long value) {
        setIssuerId(value);
        return this;
    }

    @Override
    public GuildInfractionsRecord value6(String value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public GuildInfractionsRecord values(Long value1, Long value2, Integer value3, String value4, Long value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildInfractionsRecord
     */
    public GuildInfractionsRecord() {
        super(GuildInfractions.GUILD_INFRACTIONS);
    }

    /**
     * Create a detached, initialised GuildInfractionsRecord
     */
    public GuildInfractionsRecord(Long guildId, Long targetId, Integer caseNumber, String reason, Long issuerId, String timestamp) {
        super(GuildInfractions.GUILD_INFRACTIONS);

        setGuildId(guildId);
        setTargetId(targetId);
        setCaseNumber(caseNumber);
        setReason(reason);
        setIssuerId(issuerId);
        setTimestamp(timestamp);
    }
}
