/*
 * This file is generated by jOOQ.
 */
package io.jking.tickster.jooq;


import io.jking.tickster.jooq.tables.GuildData;
import io.jking.tickster.jooq.tables.GuildReports;
import io.jking.tickster.jooq.tables.GuildTickets;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.guild_data</code>.
     */
    public static final GuildData GUILD_DATA = GuildData.GUILD_DATA;

    /**
     * The table <code>public.guild_reports</code>.
     */
    public static final GuildReports GUILD_REPORTS = GuildReports.GUILD_REPORTS;

    /**
     * The table <code>public.guild_tickets</code>.
     */
    public static final GuildTickets GUILD_TICKETS = GuildTickets.GUILD_TICKETS;
}
