/*
 * This file is generated by jOOQ.
 */
package io.jking.untitled.jooq;


import io.jking.untitled.jooq.tables.GuildData;
import io.jking.untitled.jooq.tables.GuildInfractions;
import io.jking.untitled.jooq.tables.GuildSettings;
import io.jking.untitled.jooq.tables.GuildTickets;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.guild_data</code>.
     */
    public static final GuildData GUILD_DATA = GuildData.GUILD_DATA;

    /**
     * The table <code>public.guild_infractions</code>.
     */
    public static final GuildInfractions GUILD_INFRACTIONS = GuildInfractions.GUILD_INFRACTIONS;

    /**
     * The table <code>public.guild_settings</code>.
     */
    public static final GuildSettings GUILD_SETTINGS = GuildSettings.GUILD_SETTINGS;

    /**
     * The table <code>public.guild_tickets</code>.
     */
    public static final GuildTickets GUILD_TICKETS = GuildTickets.GUILD_TICKETS;
}
