/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq.tables.records;


import io.jking.jooq.tables.GuildData;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildDataRecord extends UpdatableRecordImpl<GuildDataRecord> implements Record4<Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_data.guild_id</code>.
     */
    public GuildDataRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_data.owner_id</code>.
     */
    public GuildDataRecord setOwnerId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_data.invite_channel_id</code>.
     */
    public GuildDataRecord setInviteChannelId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.invite_channel_id</code>.
     */
    public Long getInviteChannelId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_data.log_channel_id</code>.
     */
    public GuildDataRecord setLogChannelId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.log_channel_id</code>.
     */
    public Long getLogChannelId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildData.GUILD_DATA.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildData.GUILD_DATA.OWNER_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildData.GUILD_DATA.INVITE_CHANNEL_ID;
    }

    @Override
    public Field<Long> field4() {
        return GuildData.GUILD_DATA.LOG_CHANNEL_ID;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getOwnerId();
    }

    @Override
    public Long component3() {
        return getInviteChannelId();
    }

    @Override
    public Long component4() {
        return getLogChannelId();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getOwnerId();
    }

    @Override
    public Long value3() {
        return getInviteChannelId();
    }

    @Override
    public Long value4() {
        return getLogChannelId();
    }

    @Override
    public GuildDataRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildDataRecord value2(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public GuildDataRecord value3(Long value) {
        setInviteChannelId(value);
        return this;
    }

    @Override
    public GuildDataRecord value4(Long value) {
        setLogChannelId(value);
        return this;
    }

    @Override
    public GuildDataRecord values(Long value1, Long value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildDataRecord
     */
    public GuildDataRecord() {
        super(GuildData.GUILD_DATA);
    }

    /**
     * Create a detached, initialised GuildDataRecord
     */
    public GuildDataRecord(Long guildId, Long ownerId, Long inviteChannelId, Long logChannelId) {
        super(GuildData.GUILD_DATA);

        setGuildId(guildId);
        setOwnerId(ownerId);
        setInviteChannelId(inviteChannelId);
        setLogChannelId(logChannelId);
    }

    /**
     * Create a detached, initialised GuildDataRecord
     */
    public GuildDataRecord(io.jking.jooq.tables.pojos.GuildData value) {
        super(GuildData.GUILD_DATA);

        if (value != null) {
            setGuildId(value.getGuildId());
            setOwnerId(value.getOwnerId());
            setInviteChannelId(value.getInviteChannelId());
            setLogChannelId(value.getLogChannelId());
        }
    }
}
