/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq.tables.records;


import io.jking.jooq.tables.GuildData;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildDataRecord extends UpdatableRecordImpl<GuildDataRecord> implements Record6<Long, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_data.guild_id</code>.
     */
    public GuildDataRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_data.owner_id</code>.
     */
    public GuildDataRecord setOwnerId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_data.ticket_creation_channel_id</code>.
     */
    public GuildDataRecord setTicketCreationChannelId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_creation_channel_id</code>.
     */
    public Long getTicketCreationChannelId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_data.ticket_logging_channel_id</code>.
     */
    public GuildDataRecord setTicketLoggingChannelId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_logging_channel_id</code>.
     */
    public Long getTicketLoggingChannelId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.guild_data.ticket_master_role_id</code>.
     */
    public GuildDataRecord setTicketMasterRoleId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_master_role_id</code>.
     */
    public Long getTicketMasterRoleId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.guild_data.ticket_category_id</code>.
     */
    public GuildDataRecord setTicketCategoryId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_category_id</code>.
     */
    public Long getTicketCategoryId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildData.GUILD_DATA.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildData.GUILD_DATA.OWNER_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildData.GUILD_DATA.TICKET_CREATION_CHANNEL_ID;
    }

    @Override
    public Field<Long> field4() {
        return GuildData.GUILD_DATA.TICKET_LOGGING_CHANNEL_ID;
    }

    @Override
    public Field<Long> field5() {
        return GuildData.GUILD_DATA.TICKET_MASTER_ROLE_ID;
    }

    @Override
    public Field<Long> field6() {
        return GuildData.GUILD_DATA.TICKET_CATEGORY_ID;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getOwnerId();
    }

    @Override
    public Long component3() {
        return getTicketCreationChannelId();
    }

    @Override
    public Long component4() {
        return getTicketLoggingChannelId();
    }

    @Override
    public Long component5() {
        return getTicketMasterRoleId();
    }

    @Override
    public Long component6() {
        return getTicketCategoryId();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getOwnerId();
    }

    @Override
    public Long value3() {
        return getTicketCreationChannelId();
    }

    @Override
    public Long value4() {
        return getTicketLoggingChannelId();
    }

    @Override
    public Long value5() {
        return getTicketMasterRoleId();
    }

    @Override
    public Long value6() {
        return getTicketCategoryId();
    }

    @Override
    public GuildDataRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildDataRecord value2(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public GuildDataRecord value3(Long value) {
        setTicketCreationChannelId(value);
        return this;
    }

    @Override
    public GuildDataRecord value4(Long value) {
        setTicketLoggingChannelId(value);
        return this;
    }

    @Override
    public GuildDataRecord value5(Long value) {
        setTicketMasterRoleId(value);
        return this;
    }

    @Override
    public GuildDataRecord value6(Long value) {
        setTicketCategoryId(value);
        return this;
    }

    @Override
    public GuildDataRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildDataRecord
     */
    public GuildDataRecord() {
        super(GuildData.GUILD_DATA);
    }

    /**
     * Create a detached, initialised GuildDataRecord
     */
    public GuildDataRecord(Long guildId, Long ownerId, Long ticketCreationChannelId, Long ticketLoggingChannelId, Long ticketMasterRoleId, Long ticketCategoryId) {
        super(GuildData.GUILD_DATA);

        setGuildId(guildId);
        setOwnerId(ownerId);
        setTicketCreationChannelId(ticketCreationChannelId);
        setTicketLoggingChannelId(ticketLoggingChannelId);
        setTicketMasterRoleId(ticketMasterRoleId);
        setTicketCategoryId(ticketCategoryId);
    }

    /**
     * Create a detached, initialised GuildDataRecord
     */
    public GuildDataRecord(io.jking.jooq.tables.pojos.GuildData value) {
        super(GuildData.GUILD_DATA);

        if (value != null) {
            setGuildId(value.getGuildId());
            setOwnerId(value.getOwnerId());
            setTicketCreationChannelId(value.getTicketCreationChannelId());
            setTicketLoggingChannelId(value.getTicketLoggingChannelId());
            setTicketMasterRoleId(value.getTicketMasterRoleId());
            setTicketCategoryId(value.getTicketCategoryId());
        }
    }
}
