/*
 * This file is generated by jOOQ.
 */
package io.jking.tickster.jooq.tables.records;


import io.jking.tickster.jooq.tables.GuildTickets;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildTicketsRecord extends UpdatableRecordImpl<GuildTicketsRecord> implements Record7<Integer, Long, Long, Long, Long, String, JSON> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_tickets.id</code>.
     */
    public GuildTicketsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.guild_tickets.guild_id</code>.
     */
    public GuildTicketsRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_tickets.channel_id</code>.
     */
    public GuildTicketsRecord setChannelId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.channel_id</code>.
     */
    public Long getChannelId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_tickets.category_id</code>.
     */
    public GuildTicketsRecord setCategoryId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.guild_tickets.creator_id</code>.
     */
    public GuildTicketsRecord setCreatorId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.creator_id</code>.
     */
    public Long getCreatorId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.guild_tickets.ticket_timestamp</code>.
     */
    public GuildTicketsRecord setTicketTimestamp(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.ticket_timestamp</code>.
     */
    public String getTicketTimestamp() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.guild_tickets.transcript</code>.
     */
    public GuildTicketsRecord setTranscript(JSON value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.transcript</code>.
     */
    public JSON getTranscript() {
        return (JSON) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Long, Long, Long, Long, String, JSON> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Long, Long, Long, Long, String, JSON> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GuildTickets.GUILD_TICKETS.ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildTickets.GUILD_TICKETS.GUILD_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildTickets.GUILD_TICKETS.CHANNEL_ID;
    }

    @Override
    public Field<Long> field4() {
        return GuildTickets.GUILD_TICKETS.CATEGORY_ID;
    }

    @Override
    public Field<Long> field5() {
        return GuildTickets.GUILD_TICKETS.CREATOR_ID;
    }

    @Override
    public Field<String> field6() {
        return GuildTickets.GUILD_TICKETS.TICKET_TIMESTAMP;
    }

    @Override
    public Field<JSON> field7() {
        return GuildTickets.GUILD_TICKETS.TRANSCRIPT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public Long component3() {
        return getChannelId();
    }

    @Override
    public Long component4() {
        return getCategoryId();
    }

    @Override
    public Long component5() {
        return getCreatorId();
    }

    @Override
    public String component6() {
        return getTicketTimestamp();
    }

    @Override
    public JSON component7() {
        return getTranscript();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public Long value3() {
        return getChannelId();
    }

    @Override
    public Long value4() {
        return getCategoryId();
    }

    @Override
    public Long value5() {
        return getCreatorId();
    }

    @Override
    public String value6() {
        return getTicketTimestamp();
    }

    @Override
    public JSON value7() {
        return getTranscript();
    }

    @Override
    public GuildTicketsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value3(Long value) {
        setChannelId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value4(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value5(Long value) {
        setCreatorId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value6(String value) {
        setTicketTimestamp(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value7(JSON value) {
        setTranscript(value);
        return this;
    }

    @Override
    public GuildTicketsRecord values(Integer value1, Long value2, Long value3, Long value4, Long value5, String value6, JSON value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildTicketsRecord
     */
    public GuildTicketsRecord() {
        super(GuildTickets.GUILD_TICKETS);
    }

    /**
     * Create a detached, initialised GuildTicketsRecord
     */
    public GuildTicketsRecord(Integer id, Long guildId, Long channelId, Long categoryId, Long creatorId, String ticketTimestamp, JSON transcript) {
        super(GuildTickets.GUILD_TICKETS);

        setId(id);
        setGuildId(guildId);
        setChannelId(channelId);
        setCategoryId(categoryId);
        setCreatorId(creatorId);
        setTicketTimestamp(ticketTimestamp);
        setTranscript(transcript);
    }
}
