/*
 * This file is generated by jOOQ.
 */
package io.jking.tickster.jooq.tables.records;


import io.jking.tickster.jooq.tables.GuildData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildDataRecord extends UpdatableRecordImpl<GuildDataRecord> implements Record7<Long, Long, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_data.guild_id</code>.
     */
    public GuildDataRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_data.owner_id</code>.
     */
    public GuildDataRecord setOwnerId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_data.log_id</code>.
     */
    public GuildDataRecord setLogId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.log_id</code>.
     */
    public Long getLogId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_data.support_id</code>.
     */
    public GuildDataRecord setSupportId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.support_id</code>.
     */
    public Long getSupportId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.guild_data.invite_id</code>.
     */
    public GuildDataRecord setInviteId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.invite_id</code>.
     */
    public Long getInviteId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.guild_data.category_id</code>.
     */
    public GuildDataRecord setCategoryId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.guild_data.ticket_id</code>.
     */
    public GuildDataRecord setTicketId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_data.ticket_id</code>.
     */
    public Long getTicketId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, Long, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildData.GUILD_DATA.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildData.GUILD_DATA.OWNER_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildData.GUILD_DATA.LOG_ID;
    }

    @Override
    public Field<Long> field4() {
        return GuildData.GUILD_DATA.SUPPORT_ID;
    }

    @Override
    public Field<Long> field5() {
        return GuildData.GUILD_DATA.INVITE_ID;
    }

    @Override
    public Field<Long> field6() {
        return GuildData.GUILD_DATA.CATEGORY_ID;
    }

    @Override
    public Field<Long> field7() {
        return GuildData.GUILD_DATA.TICKET_ID;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getOwnerId();
    }

    @Override
    public Long component3() {
        return getLogId();
    }

    @Override
    public Long component4() {
        return getSupportId();
    }

    @Override
    public Long component5() {
        return getInviteId();
    }

    @Override
    public Long component6() {
        return getCategoryId();
    }

    @Override
    public Long component7() {
        return getTicketId();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getOwnerId();
    }

    @Override
    public Long value3() {
        return getLogId();
    }

    @Override
    public Long value4() {
        return getSupportId();
    }

    @Override
    public Long value5() {
        return getInviteId();
    }

    @Override
    public Long value6() {
        return getCategoryId();
    }

    @Override
    public Long value7() {
        return getTicketId();
    }

    @Override
    public GuildDataRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildDataRecord value2(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public GuildDataRecord value3(Long value) {
        setLogId(value);
        return this;
    }

    @Override
    public GuildDataRecord value4(Long value) {
        setSupportId(value);
        return this;
    }

    @Override
    public GuildDataRecord value5(Long value) {
        setInviteId(value);
        return this;
    }

    @Override
    public GuildDataRecord value6(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public GuildDataRecord value7(Long value) {
        setTicketId(value);
        return this;
    }

    @Override
    public GuildDataRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildDataRecord
     */
    public GuildDataRecord() {
        super(GuildData.GUILD_DATA);
    }

    /**
     * Create a detached, initialised GuildDataRecord
     */
    public GuildDataRecord(Long guildId, Long ownerId, Long logId, Long supportId, Long inviteId, Long categoryId, Long ticketId) {
        super(GuildData.GUILD_DATA);

        setGuildId(guildId);
        setOwnerId(ownerId);
        setLogId(logId);
        setSupportId(supportId);
        setInviteId(inviteId);
        setCategoryId(categoryId);
        setTicketId(ticketId);
    }
}
