/*
 * This file is generated by jOOQ.
 */
package io.jking.tickster.jooq.tables.records;


import io.jking.tickster.jooq.tables.GuildTickets;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildTicketsRecord extends TableRecordImpl<GuildTicketsRecord> implements Record5<Long, Long, Long, LocalDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_tickets.guild_id</code>.
     */
    public GuildTicketsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_tickets.channel_id</code>.
     */
    public GuildTicketsRecord setChannelId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.channel_id</code>.
     */
    public Long getChannelId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.guild_tickets.creator_id</code>.
     */
    public GuildTicketsRecord setCreatorId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.creator_id</code>.
     */
    public Long getCreatorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_tickets.ticket_timestamp</code>.
     */
    public GuildTicketsRecord setTicketTimestamp(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.ticket_timestamp</code>.
     */
    public LocalDateTime getTicketTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.guild_tickets.status</code>.
     */
    public GuildTicketsRecord setStatus(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_tickets.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, LocalDateTime, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, LocalDateTime, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildTickets.GUILD_TICKETS.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return GuildTickets.GUILD_TICKETS.CHANNEL_ID;
    }

    @Override
    public Field<Long> field3() {
        return GuildTickets.GUILD_TICKETS.CREATOR_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return GuildTickets.GUILD_TICKETS.TICKET_TIMESTAMP;
    }

    @Override
    public Field<Boolean> field5() {
        return GuildTickets.GUILD_TICKETS.STATUS;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getChannelId();
    }

    @Override
    public Long component3() {
        return getCreatorId();
    }

    @Override
    public LocalDateTime component4() {
        return getTicketTimestamp();
    }

    @Override
    public Boolean component5() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getChannelId();
    }

    @Override
    public Long value3() {
        return getCreatorId();
    }

    @Override
    public LocalDateTime value4() {
        return getTicketTimestamp();
    }

    @Override
    public Boolean value5() {
        return getStatus();
    }

    @Override
    public GuildTicketsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value2(Long value) {
        setChannelId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value3(Long value) {
        setCreatorId(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value4(LocalDateTime value) {
        setTicketTimestamp(value);
        return this;
    }

    @Override
    public GuildTicketsRecord value5(Boolean value) {
        setStatus(value);
        return this;
    }

    @Override
    public GuildTicketsRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildTicketsRecord
     */
    public GuildTicketsRecord() {
        super(GuildTickets.GUILD_TICKETS);
    }

    /**
     * Create a detached, initialised GuildTicketsRecord
     */
    public GuildTicketsRecord(Long guildId, Long channelId, Long creatorId, LocalDateTime ticketTimestamp, Boolean status) {
        super(GuildTickets.GUILD_TICKETS);

        setGuildId(guildId);
        setChannelId(channelId);
        setCreatorId(creatorId);
        setTicketTimestamp(ticketTimestamp);
        setStatus(status);
    }
}
