/*
 * This file is generated by jOOQ.
 */
package io.jking.tickster.jooq.tables.records;


import io.jking.tickster.jooq.tables.GuildReports;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildReportsRecord extends TableRecordImpl<GuildReportsRecord> implements Record5<Long, Long[], Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guild_reports.guild_id</code>.
     */
    public GuildReportsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_reports.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guild_reports.reported_users</code>.
     */
    public GuildReportsRecord setReportedUsers(Long[] value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_reports.reported_users</code>.
     */
    public Long[] getReportedUsers() {
        return (Long[]) get(1);
    }

    /**
     * Setter for <code>public.guild_reports.issuer_id</code>.
     */
    public GuildReportsRecord setIssuerId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_reports.issuer_id</code>.
     */
    public Long getIssuerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.guild_reports.report_reason</code>.
     */
    public GuildReportsRecord setReportReason(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_reports.report_reason</code>.
     */
    public String getReportReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.guild_reports.report_timestamp</code>.
     */
    public GuildReportsRecord setReportTimestamp(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guild_reports.report_timestamp</code>.
     */
    public LocalDateTime getReportTimestamp() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long[], Long, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long[], Long, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GuildReports.GUILD_REPORTS.GUILD_ID;
    }

    @Override
    public Field<Long[]> field2() {
        return GuildReports.GUILD_REPORTS.REPORTED_USERS;
    }

    @Override
    public Field<Long> field3() {
        return GuildReports.GUILD_REPORTS.ISSUER_ID;
    }

    @Override
    public Field<String> field4() {
        return GuildReports.GUILD_REPORTS.REPORT_REASON;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return GuildReports.GUILD_REPORTS.REPORT_TIMESTAMP;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long[] component2() {
        return getReportedUsers();
    }

    @Override
    public Long component3() {
        return getIssuerId();
    }

    @Override
    public String component4() {
        return getReportReason();
    }

    @Override
    public LocalDateTime component5() {
        return getReportTimestamp();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long[] value2() {
        return getReportedUsers();
    }

    @Override
    public Long value3() {
        return getIssuerId();
    }

    @Override
    public String value4() {
        return getReportReason();
    }

    @Override
    public LocalDateTime value5() {
        return getReportTimestamp();
    }

    @Override
    public GuildReportsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildReportsRecord value2(Long[] value) {
        setReportedUsers(value);
        return this;
    }

    @Override
    public GuildReportsRecord value3(Long value) {
        setIssuerId(value);
        return this;
    }

    @Override
    public GuildReportsRecord value4(String value) {
        setReportReason(value);
        return this;
    }

    @Override
    public GuildReportsRecord value5(LocalDateTime value) {
        setReportTimestamp(value);
        return this;
    }

    @Override
    public GuildReportsRecord values(Long value1, Long[] value2, Long value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildReportsRecord
     */
    public GuildReportsRecord() {
        super(GuildReports.GUILD_REPORTS);
    }

    /**
     * Create a detached, initialised GuildReportsRecord
     */
    public GuildReportsRecord(Long guildId, Long[] reportedUsers, Long issuerId, String reportReason, LocalDateTime reportTimestamp) {
        super(GuildReports.GUILD_REPORTS);

        setGuildId(guildId);
        setReportedUsers(reportedUsers);
        setIssuerId(issuerId);
        setReportReason(reportReason);
        setReportTimestamp(reportTimestamp);
    }
}
