/*
 * This file is generated by jOOQ.
 */
package io.jking.tickster.jooq.tables;


import io.jking.tickster.jooq.Keys;
import io.jking.tickster.jooq.Public;
import io.jking.tickster.jooq.tables.records.GuildTicketsRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildTickets extends TableImpl<GuildTicketsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.guild_tickets</code>
     */
    public static final GuildTickets GUILD_TICKETS = new GuildTickets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuildTicketsRecord> getRecordType() {
        return GuildTicketsRecord.class;
    }

    /**
     * The column <code>public.guild_tickets.id</code>.
     */
    public final TableField<GuildTicketsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.guild_tickets.guild_id</code>.
     */
    public final TableField<GuildTicketsRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.channel_id</code>.
     */
    public final TableField<GuildTicketsRecord, Long> CHANNEL_ID = createField(DSL.name("channel_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.category_id</code>.
     */
    public final TableField<GuildTicketsRecord, Long> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.creator_id</code>.
     */
    public final TableField<GuildTicketsRecord, Long> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.ticket_timestamp</code>.
     */
    public final TableField<GuildTicketsRecord, String> TICKET_TIMESTAMP = createField(DSL.name("ticket_timestamp"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.open</code>.
     */
    public final TableField<GuildTicketsRecord, Boolean> OPEN = createField(DSL.name("open"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.transcript</code>.
     */
    public final TableField<GuildTicketsRecord, JSON> TRANSCRIPT = createField(DSL.name("transcript"), SQLDataType.JSON, this, "");

    private GuildTickets(Name alias, Table<GuildTicketsRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuildTickets(Name alias, Table<GuildTicketsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.guild_tickets</code> table reference
     */
    public GuildTickets(String alias) {
        this(DSL.name(alias), GUILD_TICKETS);
    }

    /**
     * Create an aliased <code>public.guild_tickets</code> table reference
     */
    public GuildTickets(Name alias) {
        this(alias, GUILD_TICKETS);
    }

    /**
     * Create a <code>public.guild_tickets</code> table reference
     */
    public GuildTickets() {
        this(DSL.name("guild_tickets"), null);
    }

    public <O extends Record> GuildTickets(Table<O> child, ForeignKey<O, GuildTicketsRecord> key) {
        super(child, key, GUILD_TICKETS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GuildTicketsRecord, Integer> getIdentity() {
        return (Identity<GuildTicketsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GuildTicketsRecord> getPrimaryKey() {
        return Keys.GUILD_TICKETS_PKEY;
    }

    @Override
    public GuildTickets as(String alias) {
        return new GuildTickets(DSL.name(alias), this);
    }

    @Override
    public GuildTickets as(Name alias) {
        return new GuildTickets(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildTickets rename(String name) {
        return new GuildTickets(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildTickets rename(Name name) {
        return new GuildTickets(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Long, Long, Long, Long, String, Boolean, JSON> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
