/*
 * This file is generated by jOOQ.
 */
package io.jking.tickster.jooq.tables;


import io.jking.tickster.jooq.Keys;
import io.jking.tickster.jooq.Public;
import io.jking.tickster.jooq.tables.records.GuildTicketsRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildTickets extends TableImpl<GuildTicketsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.guild_tickets</code>
     */
    public static final GuildTickets GUILD_TICKETS = new GuildTickets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuildTicketsRecord> getRecordType() {
        return GuildTicketsRecord.class;
    }

    /**
     * The column <code>public.guild_tickets.guild_id</code>.
     */
    public final TableField<GuildTicketsRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.channel_id</code>.
     */
    public final TableField<GuildTicketsRecord, Long> CHANNEL_ID = createField(DSL.name("channel_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.creator_id</code>.
     */
    public final TableField<GuildTicketsRecord, Long> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.guild_tickets.ticket_timestamp</code>.
     */
    public final TableField<GuildTicketsRecord, LocalDateTime> TICKET_TIMESTAMP = createField(DSL.name("ticket_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.guild_tickets.status</code>.
     */
    public final TableField<GuildTicketsRecord, Boolean> STATUS = createField(DSL.name("status"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("true", SQLDataType.BOOLEAN)), this, "");

    private GuildTickets(Name alias, Table<GuildTicketsRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuildTickets(Name alias, Table<GuildTicketsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.guild_tickets</code> table reference
     */
    public GuildTickets(String alias) {
        this(DSL.name(alias), GUILD_TICKETS);
    }

    /**
     * Create an aliased <code>public.guild_tickets</code> table reference
     */
    public GuildTickets(Name alias) {
        this(alias, GUILD_TICKETS);
    }

    /**
     * Create a <code>public.guild_tickets</code> table reference
     */
    public GuildTickets() {
        this(DSL.name("guild_tickets"), null);
    }

    public <O extends Record> GuildTickets(Table<O> child, ForeignKey<O, GuildTicketsRecord> key) {
        super(child, key, GUILD_TICKETS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<UniqueKey<GuildTicketsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.GUILD_TICKETS_CHANNEL_ID_KEY);
    }

    @Override
    public GuildTickets as(String alias) {
        return new GuildTickets(DSL.name(alias), this);
    }

    @Override
    public GuildTickets as(Name alias) {
        return new GuildTickets(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildTickets rename(String name) {
        return new GuildTickets(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildTickets rename(Name name) {
        return new GuildTickets(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, LocalDateTime, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
