/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq;


import io.jking.jooq.tables.GuildData;
import io.jking.jooq.tables.TicketData;
import io.jking.jooq.tables.TicketSettings;
import io.jking.jooq.tables.records.GuildDataRecord;
import io.jking.jooq.tables.records.TicketDataRecord;
import io.jking.jooq.tables.records.TicketSettingsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GuildDataRecord> GUILD_DATA_PKEY = Internal.createUniqueKey(GuildData.GUILD_DATA, DSL.name("guild_data_pkey"), new TableField[] { GuildData.GUILD_DATA.GUILD_ID }, true);
    public static final UniqueKey<TicketDataRecord> TICKET_DATA_PKEY = Internal.createUniqueKey(TicketData.TICKET_DATA, DSL.name("ticket_data_pkey"), new TableField[] { TicketData.TICKET_DATA.CHANNEL_ID }, true);
    public static final UniqueKey<TicketSettingsRecord> TICKET_SETTINGS_PKEY = Internal.createUniqueKey(TicketSettings.TICKET_SETTINGS, DSL.name("ticket_settings_pkey"), new TableField[] { TicketSettings.TICKET_SETTINGS.GUILD_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TicketDataRecord, GuildDataRecord> TICKET_DATA__TICKET_DATA_GUILD_ID_FKEY = Internal.createForeignKey(TicketData.TICKET_DATA, DSL.name("ticket_data_guild_id_fkey"), new TableField[] { TicketData.TICKET_DATA.GUILD_ID }, Keys.GUILD_DATA_PKEY, new TableField[] { GuildData.GUILD_DATA.GUILD_ID }, true);
    public static final ForeignKey<TicketSettingsRecord, GuildDataRecord> TICKET_SETTINGS__TICKET_SETTINGS_GUILD_ID_FKEY = Internal.createForeignKey(TicketSettings.TICKET_SETTINGS, DSL.name("ticket_settings_guild_id_fkey"), new TableField[] { TicketSettings.TICKET_SETTINGS.GUILD_ID }, Keys.GUILD_DATA_PKEY, new TableField[] { GuildData.GUILD_DATA.GUILD_ID }, true);
}
