/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq;


import io.jking.jooq.tables.GuildData;
import io.jking.jooq.tables.TicketData;
import io.jking.jooq.tables.TicketSettings;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.guild_data</code>.
     */
    public final GuildData GUILD_DATA = GuildData.GUILD_DATA;

    /**
     * The table <code>public.ticket_data</code>.
     */
    public final TicketData TICKET_DATA = TicketData.TICKET_DATA;

    /**
     * The table <code>public.ticket_settings</code>.
     */
    public final TicketSettings TICKET_SETTINGS = TicketSettings.TICKET_SETTINGS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            GuildData.GUILD_DATA,
            TicketData.TICKET_DATA,
            TicketSettings.TICKET_SETTINGS
        );
    }
}
