/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq;


import io.jking.jooq.tables.ActiveTicketData;
import io.jking.jooq.tables.GuildData;
import io.jking.jooq.tables.GuildTicketBlacklist;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.active_ticket_data</code>.
     */
    public final ActiveTicketData ACTIVE_TICKET_DATA = ActiveTicketData.ACTIVE_TICKET_DATA;

    /**
     * The table <code>public.guild_data</code>.
     */
    public final GuildData GUILD_DATA = GuildData.GUILD_DATA;

    /**
     * The table <code>public.guild_ticket_blacklist</code>.
     */
    public final GuildTicketBlacklist GUILD_TICKET_BLACKLIST = GuildTicketBlacklist.GUILD_TICKET_BLACKLIST;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ActiveTicketData.ACTIVE_TICKET_DATA,
            GuildData.GUILD_DATA,
            GuildTicketBlacklist.GUILD_TICKET_BLACKLIST
        );
    }
}
