/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq;


import io.jking.jooq.tables.ActiveTicketData;
import io.jking.jooq.tables.GuildData;
import io.jking.jooq.tables.GuildTicketBlacklist;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.active_ticket_data</code>.
     */
    public static final ActiveTicketData ACTIVE_TICKET_DATA = ActiveTicketData.ACTIVE_TICKET_DATA;

    /**
     * The table <code>public.guild_data</code>.
     */
    public static final GuildData GUILD_DATA = GuildData.GUILD_DATA;

    /**
     * The table <code>public.guild_ticket_blacklist</code>.
     */
    public static final GuildTicketBlacklist GUILD_TICKET_BLACKLIST = GuildTicketBlacklist.GUILD_TICKET_BLACKLIST;
}
