/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq;


import io.jking.jooq.tables.GuildData;
import io.jking.jooq.tables.TicketData;
import io.jking.jooq.tables.TicketSettings;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.guild_data</code>.
     */
    public static final GuildData GUILD_DATA = GuildData.GUILD_DATA;

    /**
     * The table <code>public.ticket_data</code>.
     */
    public static final TicketData TICKET_DATA = TicketData.TICKET_DATA;

    /**
     * The table <code>public.ticket_settings</code>.
     */
    public static final TicketSettings TICKET_SETTINGS = TicketSettings.TICKET_SETTINGS;
}
