/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActiveTicketData implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long    channelId;
    private final Long    guildId;
    private final Long    creatorId;
    private final Boolean allowTranscript;

    public ActiveTicketData(ActiveTicketData value) {
        this.channelId = value.channelId;
        this.guildId = value.guildId;
        this.creatorId = value.creatorId;
        this.allowTranscript = value.allowTranscript;
    }

    public ActiveTicketData(
        Long    channelId,
        Long    guildId,
        Long    creatorId,
        Boolean allowTranscript
    ) {
        this.channelId = channelId;
        this.guildId = guildId;
        this.creatorId = creatorId;
        this.allowTranscript = allowTranscript;
    }

    /**
     * Getter for <code>public.active_ticket_data.channel_id</code>.
     */
    public Long getChannelId() {
        return this.channelId;
    }

    /**
     * Getter for <code>public.active_ticket_data.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.active_ticket_data.creator_id</code>.
     */
    public Long getCreatorId() {
        return this.creatorId;
    }

    /**
     * Getter for <code>public.active_ticket_data.allow_transcript</code>.
     */
    public Boolean getAllowTranscript() {
        return this.allowTranscript;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActiveTicketData (");

        sb.append(channelId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(allowTranscript);

        sb.append(")");
        return sb.toString();
    }
}
