/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildData implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long guildId;
    private final Long ownerId;
    private final Long inviteChannelId;
    private final Long logChannelId;

    public GuildData(GuildData value) {
        this.guildId = value.guildId;
        this.ownerId = value.ownerId;
        this.inviteChannelId = value.inviteChannelId;
        this.logChannelId = value.logChannelId;
    }

    public GuildData(
        Long guildId,
        Long ownerId,
        Long inviteChannelId,
        Long logChannelId
    ) {
        this.guildId = guildId;
        this.ownerId = ownerId;
        this.inviteChannelId = inviteChannelId;
        this.logChannelId = logChannelId;
    }

    /**
     * Getter for <code>public.guild_data.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.guild_data.owner_id</code>.
     */
    public Long getOwnerId() {
        return this.ownerId;
    }

    /**
     * Getter for <code>public.guild_data.invite_channel_id</code>.
     */
    public Long getInviteChannelId() {
        return this.inviteChannelId;
    }

    /**
     * Getter for <code>public.guild_data.log_channel_id</code>.
     */
    public Long getLogChannelId() {
        return this.logChannelId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GuildData (");

        sb.append(guildId);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(inviteChannelId);
        sb.append(", ").append(logChannelId);

        sb.append(")");
        return sb.toString();
    }
}
