/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildData implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long guildId;
    private final Long ownerId;
    private final Long ticketCreationChannelId;
    private final Long ticketLoggingChannelId;
    private final Long ticketMasterRoleId;
    private final Long ticketCategoryId;

    public GuildData(GuildData value) {
        this.guildId = value.guildId;
        this.ownerId = value.ownerId;
        this.ticketCreationChannelId = value.ticketCreationChannelId;
        this.ticketLoggingChannelId = value.ticketLoggingChannelId;
        this.ticketMasterRoleId = value.ticketMasterRoleId;
        this.ticketCategoryId = value.ticketCategoryId;
    }

    public GuildData(
        Long guildId,
        Long ownerId,
        Long ticketCreationChannelId,
        Long ticketLoggingChannelId,
        Long ticketMasterRoleId,
        Long ticketCategoryId
    ) {
        this.guildId = guildId;
        this.ownerId = ownerId;
        this.ticketCreationChannelId = ticketCreationChannelId;
        this.ticketLoggingChannelId = ticketLoggingChannelId;
        this.ticketMasterRoleId = ticketMasterRoleId;
        this.ticketCategoryId = ticketCategoryId;
    }

    /**
     * Getter for <code>public.guild_data.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.guild_data.owner_id</code>.
     */
    public Long getOwnerId() {
        return this.ownerId;
    }

    /**
     * Getter for <code>public.guild_data.ticket_creation_channel_id</code>.
     */
    public Long getTicketCreationChannelId() {
        return this.ticketCreationChannelId;
    }

    /**
     * Getter for <code>public.guild_data.ticket_logging_channel_id</code>.
     */
    public Long getTicketLoggingChannelId() {
        return this.ticketLoggingChannelId;
    }

    /**
     * Getter for <code>public.guild_data.ticket_master_role_id</code>.
     */
    public Long getTicketMasterRoleId() {
        return this.ticketMasterRoleId;
    }

    /**
     * Getter for <code>public.guild_data.ticket_category_id</code>.
     */
    public Long getTicketCategoryId() {
        return this.ticketCategoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GuildData (");

        sb.append(guildId);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(ticketCreationChannelId);
        sb.append(", ").append(ticketLoggingChannelId);
        sb.append(", ").append(ticketMasterRoleId);
        sb.append(", ").append(ticketCategoryId);

        sb.append(")");
        return sb.toString();
    }
}
