/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketData implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          channelId;
    private final Long          guildId;
    private final Long          creatorId;
    private final LocalDateTime creation;
    private final LocalDateTime expiry;

    public TicketData(TicketData value) {
        this.channelId = value.channelId;
        this.guildId = value.guildId;
        this.creatorId = value.creatorId;
        this.creation = value.creation;
        this.expiry = value.expiry;
    }

    public TicketData(
        Long          channelId,
        Long          guildId,
        Long          creatorId,
        LocalDateTime creation,
        LocalDateTime expiry
    ) {
        this.channelId = channelId;
        this.guildId = guildId;
        this.creatorId = creatorId;
        this.creation = creation;
        this.expiry = expiry;
    }

    /**
     * Getter for <code>public.ticket_data.channel_id</code>.
     */
    public Long getChannelId() {
        return this.channelId;
    }

    /**
     * Getter for <code>public.ticket_data.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.ticket_data.creator_id</code>.
     */
    public Long getCreatorId() {
        return this.creatorId;
    }

    /**
     * Getter for <code>public.ticket_data.creation</code>.
     */
    public LocalDateTime getCreation() {
        return this.creation;
    }

    /**
     * Getter for <code>public.ticket_data.expiry</code>.
     */
    public LocalDateTime getExpiry() {
        return this.expiry;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TicketData (");

        sb.append(channelId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(creation);
        sb.append(", ").append(expiry);

        sb.append(")");
        return sb.toString();
    }
}
