/*
 * This file is generated by jOOQ.
 */
package io.jking.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketSettings implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long guildId;
    private final Long categoryId;
    private final Long ticketChannelId;
    private final Long ticketSupportRoleId;

    public TicketSettings(TicketSettings value) {
        this.guildId = value.guildId;
        this.categoryId = value.categoryId;
        this.ticketChannelId = value.ticketChannelId;
        this.ticketSupportRoleId = value.ticketSupportRoleId;
    }

    // This is a custom constructor to allow for default values.
    public TicketSettings(
            long guildId
    ) {
        this.guildId = guildId;
        this.categoryId = 0L;
        this.ticketChannelId = 0L;
        this.ticketSupportRoleId = 0L;
    }

    public TicketSettings(
        Long guildId,
        Long categoryId,
        Long ticketChannelId,
        Long ticketSupportRoleId
    ) {
        this.guildId = guildId;
        this.categoryId = categoryId;
        this.ticketChannelId = ticketChannelId;
        this.ticketSupportRoleId = ticketSupportRoleId;
    }

    /**
     * Getter for <code>public.ticket_settings.guild_id</code>.
     */
    public Long getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.ticket_settings.category_id</code>.
     */
    public Long getCategoryId() {
        return this.categoryId;
    }

    /**
     * Getter for <code>public.ticket_settings.ticket_channel_id</code>.
     */
    public Long getTicketChannelId() {
        return this.ticketChannelId;
    }

    /**
     * Getter for <code>public.ticket_settings.ticket_support_role_id</code>.
     */
    public Long getTicketSupportRoleId() {
        return this.ticketSupportRoleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TicketSettings (");

        sb.append(guildId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(ticketChannelId);
        sb.append(", ").append(ticketSupportRoleId);

        sb.append(")");
        return sb.toString();
    }
}
